//Console.WriteLine(AoC2022.Day1.PartOne.Solution());
//Console.WriteLine(AoC2022.Day1.PartTwo.Solution());
//Console.WriteLine(AoC2022.Day2.PartOne.Solution());
//Console.WriteLine(AoC2022.Day2.PartOne.Solution());
//Console.WriteLine(await AoC2022.Day3.PartOne.Solution());
//Console.WriteLine(await AoC2022.Day3.PartTwo.Solution());
//Console.WriteLine(await AoC2022.Day4.PartOne.Solution());
//Console.WriteLine(await AoC2022.Day4.PartTwo.Solution());
//Console.WriteLine(AoC2022.Day5.PartOne.Solution());
//Console.WriteLine(AoC2022.Day5.PartTwo.Solution());
//Console.WriteLine(AoC2022.Day6.PartOne.Solution());
//Console.WriteLine(AoC2022.Day6.PartTwo.Solution());
//Console.WriteLine(AoC2022.Day7.PartOne.Solution());
//Console.WriteLine(AoC2022.Day7.PartTwo.Solution());
//Console.WriteLine(AoC2022.Day8.PartOne.Solution());
//Console.WriteLine(AoC2022.Day8.PartTwo.Solution());
//Console.WriteLine(AoC2022.Day9.PartOne.Solution());
//Console.WriteLine(AoC2022.Day9.PartTwo.Solution());
//Console.WriteLine(AoC2022.Day10.PartOne.Solution());
//AoC2022.Day10.PartTwo.Solution();
//Console.WriteLine(AoC2022.Day11.PartOne.Solution());
//Console.WriteLine(AoC2022.Day11.PartTwo.Solution());
//Console.WriteLine(AoC2022.Day11.PartOne.Solution());
//Console.WriteLine(AoC2022.Day12.PartOne.Solution());
//Console.WriteLine(AoC2022.Day12.PartTwo.Solution());
Console.WriteLine(AoC2022.Day13.PartOne.Solution());